In [46]:
import numpy as np
import tensorflow as tf

In [47]:
observation = 1500
x1 = np.random.uniform(-10,10,(observation,1))
x2 = np.random.uniform(-10,10,(observation,1))
inputs = np.column_stack((x1,x2))
noise = np.random.uniform(-1,1,(observation,1))
targets = -2 * x1 + 6 * x2 + 13 + noise
np.savez('data',inputs=inputs,targets=targets)

In [48]:
training_data = np.load("data.npz")
inputSize = 2
outputSize = 1


In [49]:
model = tf.keras.Sequential([tf.keras.layers.Dense(outputSize,
                                                   kernel_initializer=tf.random_uniform_initializer(-0.1,0.1),
                                                   bias_initializer=tf.random_uniform_initializer(-0.1,0.1)
                                                   )
                             ])
optimizer = tf.keras.optimizers.SGD(0.02)
model.compile(optimizer=optimizer,loss="mean_squared_error")
model.fit(training_data["inputs"],training_data["targets"],epochs=200,verbose=2)

Epoch 1/200
1500/1500 - 0s - loss: 81.5192
Epoch 2/200
1500/1500 - 0s - loss: 1.3475
Epoch 3/200
1500/1500 - 0s - loss: 0.3875
Epoch 4/200
1500/1500 - 0s - loss: 0.3473
Epoch 5/200
1500/1500 - 0s - loss: 0.3528
Epoch 6/200
1500/1500 - 0s - loss: 0.3488
Epoch 7/200
1500/1500 - 0s - loss: 0.3617
Epoch 8/200
1500/1500 - 0s - loss: 0.3550
Epoch 9/200
1500/1500 - 0s - loss: 0.3626
Epoch 10/200
1500/1500 - 0s - loss: 0.3641
Epoch 11/200
1500/1500 - 0s - loss: 0.3814
Epoch 12/200
1500/1500 - 0s - loss: 0.3694
Epoch 13/200
1500/1500 - 0s - loss: 0.3544
Epoch 14/200
1500/1500 - 0s - loss: 0.3675
Epoch 15/200
1500/1500 - 0s - loss: 0.3713
Epoch 16/200
1500/1500 - 0s - loss: 0.3798
Epoch 17/200
1500/1500 - 0s - loss: 0.3471
Epoch 18/200
1500/1500 - 0s - loss: 0.3577
Epoch 19/200
1500/1500 - 0s - loss: 0.3757
Epoch 20/200
1500/1500 - 0s - loss: 0.3562
Epoch 21/200
1500/1500 - 0s - loss: 0.3835
Epoch 22/200
1500/1500 - 0s - loss: 0.3660
Epoch 23/200
1500/1500 - 0s - loss: 0.3559
Epoch 24/200
1500/1

In [50]:
model.layers[0].get_weights()

[array([[-1.9756924],
        [ 5.9954324]], dtype=float32),
 array([12.992966], dtype=float32)]

In [51]:
model.layers[0].get_weights()[0]

array([[-1.9756924],
       [ 5.9954324]], dtype=float32)

In [52]:
model.layers[0].get_weights()[1]



array([12.992966], dtype=float32)